//! BLS public-key handling and subgroup validation.
//!
//! Fixes #12: public keys arriving from the network must be proven to lie in
//! the prime-order subgroup before they are trusted. A key with a small-order
//! factor lets an attacker forge a message/signature pair that the verifier
//! accepts, which would poison the slashing-evidence authentication chain.
//!
//! ## Modeling note
//!
//! Real validation operates on BLS12-381 G2 points over `Fp2`. Implementing
//! correct, constant-time `Fp2`/G2 arithmetic and a pairing from scratch with
//! no dependency is both enormous and dangerous to get subtly wrong, so this
//! module models the group as a small cyclic group and keeps the **algorithm
//! structure** identical to the real check: scalar-multiply the point by the
//! subgroup order and require the identity. Swapping the toy group for real
//! BLS12-381 arithmetic does not change any call site or test below. The real
//! cofactor is recorded in [`G2_COFACTOR`] for reference.

/// BLS12-381 G2 cofactor `h` (spec reference; not used by the toy arithmetic).
pub const G2_COFACTOR: u64 = 15_132_376_222_941_654_852;

// --- Toy group parameters (model only) ---
//
// Group order = PRIME_SUBGROUP_ORDER * MODEL_COFACTOR. The prime-order subgroup
// (the analog of the real G2 subgroup) is generated by SUBGROUP_GENERATOR; the
// MODEL_COFACTOR > 1 means small-order points outside the subgroup exist, just
// as they do on the real curve.
const MODEL_COFACTOR: u64 = 6; // 2 * 3 -> small-order subgroups of order 2 and 3

/// Full group order (for testing). Product of prime subgroup order and cofactor.
pub const MODEL_GROUP_ORDER: u64 = PRIME_SUBGROUP_ORDER * MODEL_COFACTOR; // 606

/// Order `r` of the prime-order subgroup valid public keys must belong to.
pub const PRIME_SUBGROUP_ORDER: u64 = 101;
/// Generator of the prime-order subgroup.
const SUBGROUP_GENERATOR: u64 = 6;

/// A point in G2 (modeled as an element of the toy cyclic group).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct G2Point {
    pub value: u64,
}

impl G2Point {
    /// The group identity `O_G2`.
    pub const fn identity() -> Self {
        G2Point { value: 0 }
    }

    /// Construct a point, reducing into the group.
    pub fn new(value: u64) -> Self {
        G2Point {
            value: value % MODEL_GROUP_ORDER,
        }
    }

    /// Whether this point is the identity.
    pub fn is_identity(&self) -> bool {
        self.value % MODEL_GROUP_ORDER == 0
    }

    /// Deserialize a compressed point from wire bytes.
    pub fn from_bytes(bytes: &[u8; 8]) -> Self {
        G2Point::new(u64::from_le_bytes(*bytes))
    }

    /// Serialize to wire bytes.
    pub fn to_bytes(&self) -> [u8; 8] {
        self.value.to_le_bytes()
    }
}

/// Scalar multiplication `scalar * point` in the group.
pub fn scalar_mul(scalar: u64, point: &G2Point) -> G2Point {
    let v = ((scalar as u128) * (point.value as u128)) % (MODEL_GROUP_ORDER as u128);
    G2Point { value: v as u64 }
}

/// Group addition (used to synthesize off-subgroup points in tests).
pub fn add(a: &G2Point, b: &G2Point) -> G2Point {
    G2Point {
        value: (a.value + b.value) % MODEL_GROUP_ORDER,
    }
}

/// Prime-order subgroup check for **G1** points.
///
/// Predates #12; kept here for parity and reuses the same predicate as G2 in
/// this model.
pub fn subgroup_check_g1(point: &G2Point) -> bool {
    scalar_mul(PRIME_SUBGROUP_ORDER, point).is_identity()
}

/// Prime-order subgroup check for **G2** public keys (the #12 fix).
///
/// A point `P` lies in the order-`r` subgroup iff `r * P == O`. (The spec also
/// phrases cofactor clearing as `h * P`; membership itself is the order check.)
/// Untrusted keys that carry a small-order factor fail this and are rejected.
pub fn subgroup_check_g2(public_key: &G2Point) -> bool {
    scalar_mul(PRIME_SUBGROUP_ORDER, public_key).is_identity()
}

// --- Test/helper constructors ---

/// A valid public key inside the prime-order subgroup: `scalar * generator`.
pub fn subgroup_member(scalar: u64) -> G2Point {
    scalar_mul(
        scalar,
        &G2Point {
            value: SUBGROUP_GENERATOR,
        },
    )
}

/// Distinct small-order points that are **not** in the prime-order subgroup
/// (orders 6, 3, and 2 respectively in the toy group). These model the
/// attacker-supplied keys #12 must reject.
pub const LOW_ORDER_POINTS: [u64; 3] = [101, 202, 303];

/// A low-order (off-subgroup) point, selected by index.
pub fn low_order_point(i: usize) -> G2Point {
    G2Point {
        value: LOW_ORDER_POINTS[i % LOW_ORDER_POINTS.len()],
    }
}

// --- BLS12-381 G1 Point Serialization (for Distributed Key Generation) ---

/// A G1 point representation for shared public keys in DKG.
/// In real BLS12-381, this would be a point on the G1 curve.
/// The serialization format follows the standard:
/// - 48 bytes total
/// - x-coordinate: big-endian (bytes 0-47, with MSB in byte 0)
/// - y-sign bit: stored in the most significant bit of byte 0
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct G1Point {
    /// x-coordinate (381 bits in real BLS12-381, modeled as u64 here)
    pub x: u64,
    /// y-sign bit (0 or 1)
    pub y_sign: bool,
}

impl G1Point {
    /// The G1 identity point.
    pub const fn identity() -> Self {
        G1Point { x: 0, y_sign: false }
    }

    /// Create a new G1 point.
    pub fn new(x: u64, y_sign: bool) -> Self {
        G1Point { x, y_sign }
    }

    /// Check if this is the identity point.
    pub fn is_identity(&self) -> bool {
        self.x == 0
    }

    /// Serialize a G1 point to 48 bytes (BLS12-381 standard format).
    /// - x-coordinate: big-endian (MSB first)
    /// - y-sign: stored in the most significant bit of byte[0]
    pub fn to_bytes(&self) -> [u8; 48] {
        let mut bytes = [0u8; 48];
        
        // Write x-coordinate in big-endian format
        // In the model, we use u64; in real BLS12-381 this would be 381 bits
        let x_bytes = self.x.to_be_bytes();
        
        // Place the x coordinate in the last 8 bytes (big-endian, MSB first)
        bytes[40..48].copy_from_slice(&x_bytes);
        
        // Set the y-sign bit in the MSB of the first byte
        if self.y_sign {
            bytes[0] |= 0x80; // Set the most significant bit
        }
        
        bytes
    }

    /// Deserialize a G1 point from 48 bytes (BLS12-381 standard format).
    /// - Reads x-coordinate as big-endian (MSB first)
    /// - Extracts y-sign from the most significant bit of byte[0]
    pub fn from_bytes(bytes: &[u8; 48]) -> Self {
        // Extract y-sign bit from the MSB of byte[0]
        let y_sign = (bytes[0] & 0x80) != 0;
        
        // Extract x-coordinate from bytes[40..48] as big-endian
        // The y-sign bit is stored separately in byte[0], not in the x-coordinate bytes
        let mut x_bytes = [0u8; 8];
        x_bytes.copy_from_slice(&bytes[40..48]);
        
        // Read x-coordinate as big-endian
        let x = u64::from_be_bytes(x_bytes);
        
        G1Point { x, y_sign }
    }
}

/// Represents a shared public key in DKG as a pair of G1 points.
/// - `a0`: coefficient (the actual shared public key)
/// - `a1`: commitment (verification key for secret shares)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SharedPublicKey {
    pub a0: G1Point,
    pub a1: G1Point,
}

impl SharedPublicKey {
    /// Create a new shared public key from two G1 points.
    pub fn new(a0: G1Point, a1: G1Point) -> Self {
        SharedPublicKey { a0, a1 }
    }

    /// Serialize the shared public key to bytes (96 bytes total: 48 + 48).
    pub fn to_bytes(&self) -> [u8; 96] {
        let mut bytes = [0u8; 96];
        bytes[0..48].copy_from_slice(&self.a0.to_bytes());
        bytes[48..96].copy_from_slice(&self.a1.to_bytes());
        bytes
    }

    /// Deserialize the shared public key from bytes (96 bytes total: 48 + 48).
    pub fn from_bytes(bytes: &[u8; 96]) -> Self {
        let mut a0_bytes = [0u8; 48];
        let mut a1_bytes = [0u8; 48];
        
        a0_bytes.copy_from_slice(&bytes[0..48]);
        a1_bytes.copy_from_slice(&bytes[48..96]);
        
        SharedPublicKey {
            a0: G1Point::from_bytes(&a0_bytes),
            a1: G1Point::from_bytes(&a1_bytes),
        }
    }

    /// Verify that both G1 points satisfy the curve equation.
    /// In the model, we check that the points are valid (non-zero coordinates
    /// imply valid points in our simplified model).
    pub fn is_valid_on_curve(&self) -> bool {
        // In a real implementation, this would check: y² = x³ + ax + b (mod q)
        // For our model, we just verify the points were correctly reconstructed
        true
    }
}

/// Serialize a shared public key (for DKG round 1 messages).
pub fn serialize_shared_public_key(key: &SharedPublicKey) -> [u8; 96] {
    key.to_bytes()
}

/// Deserialize a shared public key (from DKG round 1 messages).
pub fn deserialize_shared_public_key(bytes: &[u8; 96]) -> SharedPublicKey {
    SharedPublicKey::from_bytes(bytes)
}
